tmctl dump - Add support for Docker-Compose & DigitalOcean
triggermesh/tmctl pull request #197
Opened 2022-12-21 16:03 UTC by FranBarrera

Added a new parameter to tmctl dump [--platform| -p] with multiple platforms [kubernetes | knative | docker-compose | digitalocean]. By default is kubernetes.

Example:
```
tmctl dump -p docker-compose

services:
  console:
    container_name: console
    environment: []
    image: gcr.io/triggermesh/triggermesh-console:v0.0.1
    ports:
    - 54772:8080
    volumes: []
  foo:
    command: start --memory.buffer-size 100 --memory.produce-timeout 1s --broker-config-path
      /etc/triggermesh/broker.conf
    container_name: foo
    environment: []
    image: gcr.io/triggermesh/memory-broker:latest
    ports:
    - 54758:8080
    volumes:
    - source: /Users/fran/.triggermesh/cli/foo/broker.conf
      target: /etc/triggermesh/broker.conf
      type: bind
  foo-httppollersource:
    container_name: foo-httppollersource
    environment:
    - HTTPPOLLER_EVENT_TYPE=buzzword.phrase
    - HTTPPOLLER_EVENT_SOURCE=local.foo-httppollersource
    - HTTPPOLLER_ENDPOINT=https://corporatebs-generator.sameerkumar.website/
    - HTTPPOLLER_METHOD=GET
    - HTTPPOLLER_SKIP_VERIFY=false
    - HTTPPOLLER_INTERVAL=20s
    - K_SINK=http://host.docker.internal:54758
    image: gcr.io/triggermesh/httppollersource-adapter:v1.22.0
    ports:
    - "8080"
    volumes: []
  foo-transformation:
    container_name: foo-transformation
    environment:
    - TRANSFORMATION_CONTEXT=[{"operation":"add","paths":[{"key":"type","value":"foo-transformation.output"}]}]
    - TRANSFORMATION_DATA=[{"operation":"add","paths":[{"key":"new-field","value":"hello
      from Transformation!"}]}]
    image: gcr.io/triggermesh/transformation-adapter:v1.22.0
    ports:
    - 54777:8080
    volumes: []
```

2022-12-21 18:59 UTC, sebgoa commented
it works.

but for DO:

- sources need to be of type `workers` and not `services`
- the sources need to sink to the broker with a route of `/broker` like
```
  - key: K_SINK
    scope: RUN_AND_BUILD_TIME
    value: ${broker.PRIVATE_URL}/broker
```
- the broker is indeed of type `services` but with a route set to `broker` like:
```
  name: broker
  routes:
  - path: /broker
```

2022-12-21 21:40 UTC, sebgoa commented
Can you remove the `gcr.io/triggermesh` from the DO dump. Those images will need to be in the DO registry, right now we can reference them implicitly with only the adapter name.

For compose the full gcr.io/triggermesh name is correct.

2022-12-22 08:09 UTC, tzununbekov requested changes

2022-12-22 08:09 UTC, tzununbekov commented on pkg/triggermesh/interfaces.go
> +type Platform interface {
The interface name should reflect its behavior, like `triggermesh.Runnable` or `triggermesh.Reconcilable`. The use of this interface in the code, `triggermesh.Platform`, has a misleading notion. Any option would fit - `Dumpable`, `Exportable`, `Convertible`.:

`component.(triggermesh.Platform).AsDigitalOcean` vs. `component.(triggermesh.Exportable).AsDigitalOceanObject`

2022-12-22 12:09 UTC, FranBarrera commented on pkg/triggermesh/components/broker/broker.go
> +	port, err := b.GetPort(context.Background())
It's this way, getting the broker, service, target port, or setting a manual port (harcoded), I choose this way, also I think it will be easier for users to use the same ports, but yes it requires to do the dump with the containers running with tmctl.

2022-12-22 12:38 UTC, tzununbekov commented on pkg/triggermesh/components/broker/broker.go
> +	port, err := b.GetPort(context.Background())
How is trying to re-use already occupied ports is easier for users (especially if it requires components to be running) comparing to just picking random (open) private port?

2022-12-22 15:01 UTC, FranBarrera commented on pkg/triggermesh/components/broker/broker.go
> +	port, err := b.GetPort(context.Background())
It'll use the already occupied ports to fill a yaml file, it doesn't make any sense to run the same containers in the same machine with docker and with docker-compose

2022-12-22 16:04 UTC, FranBarrera commented
@sebgoa DO issues should be fine now

2022-12-22 17:42 UTC, tzununbekov commented on pkg/triggermesh/components/broker/broker.go
> +	port, err := b.GetPort(context.Background())
I'm still struggling to understand - how is it easier than just picking a new port?
If you could provide a single reason to stick to this logic, I'll gladly consider it, but now all what I see is:
1. It brings illogical requirement to keep components running to create a manifest. Our `dump` command currently require users to stop local env to avoid race conditions between multiple deployment; with this change it will require the opposite - to start it 🤷‍♂️ 
2. What I suggest is much more simple comparing to what proposed in this PR from both UX and development experience. Just one line to get a new port instead of creating new component instances to lookup their ports.

If there is some requirement to match the ports or you see possible shortcomings in my recommendation, then let's bring them up and come up with the solution that would satisfy both of us. Otherwise I don't understand what is it all about.

2022-12-23 08:53 UTC, FranBarrera commented on pkg/triggermesh/components/broker/broker.go
> +	port, err := b.GetPort(context.Background())
Well users will be able to do the same curls to the existing services/targets that they created with tmctl, for me it's a bit weird to do the dump to docker-compose and could not reach the same services with the same ports since it's a dump. Also we can't let docker to auto assign a random port because we will need to create the broker config with these ports, so we will need to generate it, save it and then put it in the docker-compose and broker config

2022-12-23 10:10 UTC, tzununbekov commented on pkg/triggermesh/components/broker/broker.go
> +	port, err := b.GetPort(context.Background())
ah, I think I finally see why you did this - you're mounting CLI's broker config directly in docker-compose and you want all ports to match the existing config to make it work:

```
tmctl dump -p docker-compose
...
    volumes:
    - source: /Users/tzununbekov/.triggermesh/cli/foo/broker.conf
      target: /etc/triggermesh/broker.conf
      type: bind
```

I'm sorry, but I don't think that it should be this way. And the reason "to do the same curls" is not worth considering because as you said - "it doesn't make any sense to run the same containers in the same machine". 
These dump manifests are designed to run on different machines, remote servers, CI hosts, etc. and to require user's CLI to be there is not the way to go.
This issue needs to be addressed before merging the PR.

2022-12-28 12:17 UTC, sebgoa commented
This could be a follow on ticket.

When there are more than one services (i.e targets) each should have its own route (instead of being just root /) and this should get reflected in the broker config if need be.

2023-01-02 10:15 UTC, sebgoa commented on cmd/dump/dump.go
> +			Name:     "triggermesh",
That `Name` should be randomized a bit maybe with a short random suffix

2023-01-10 11:08 UTC, sebgoa commented
A bit dirty but I am putting a diff here so that I don't loose it

```
$ git diff cmd/dump/dump.go
diff --git a/cmd/dump/dump.go b/cmd/dump/dump.go
index fdaeba8..492f4ba 100644
--- a/cmd/dump/dump.go
+++ b/cmd/dump/dump.go
@@ -25,6 +25,7 @@ import (
        "strings"
 
        "github.com/digitalocean/godo"
+       "github.com/google/uuid"
        "github.com/spf13/cobra"
        "github.com/spf13/viper"
 
@@ -147,7 +148,7 @@ func (o *dumpOptions) dump() error {
                                                targetURL = fmt.Sprintf("http://%s:8080", target.Ref.Name)
                                        }
                                        if o.Platform == platformDigitalOcean {
-                                               targetURL = fmt.Sprintf("${%s.PRIVATE_URL}", target.Ref.Name)
+                                               targetURL = fmt.Sprintf("${%s.PRIVATE_URL}/%s", target.Ref.Name, target.Ref.Name)
                                        }
                                        trigger := tmbroker.LocalTriggerSpec{}
                                        filter := eventingbroker.Filter{}
@@ -214,7 +215,7 @@ func (o *dumpOptions) dump() error {
                        }
                }
                doObject := godo.AppSpec{
-                       Name:     "triggermesh",
+                       Name:     "triggermesh-" + uuid.NewString()[:5],
                        Services: doServices,
                        Workers:  doWorkers,
                        Region:   "fra",
(⎈ |prod:sebgoa)MacBook-Air:tmctl sebgoa$ git diff pkg/triggermesh/components/target/target.go
diff --git a/pkg/triggermesh/components/target/target.go b/pkg/triggermesh/components/target/target.go
index 20f6eb2..1407568 100644
--- a/pkg/triggermesh/components/target/target.go
+++ b/pkg/triggermesh/components/target/target.go
@@ -156,7 +156,7 @@ func (t *Target) AsDigitalOcean(additionalEnvs map[string]string) (*digitalocean
                HTTPPort: 8080,
                Routes: []*godo.AppRouteSpec{
                        {
-                               Path: "/",
+                               Path: "/" + t.Name,
                        },
                },
                Envs:
```

2023-01-11 15:27 UTC, sebgoa approved these changes
first functionality is there. so I am approving.

thanks for switching the transformation to a ServiceSpec

2023-01-12 11:35 UTC, FranBarrera commented on pkg/triggermesh/components/target/target.go
> +				Path: "/",
I guess this is old

2023-01-18 07:53 UTC, tzununbekov commented
Looks like I cannot merge my [branch](https://github.com/triggermesh/tmctl/compare/main...dump-multi-platforms) with this PR because it is based on the personal fork. @FranBarrera could you cherry-pick 30179283e388e48a6903820f6b608f1c14912054? Alternatively, we can merge this one and then mine on the top, but cherry-picking is preferable to keep the change history clean.

2023-01-19 09:00 UTC, tzununbekov approved these changes

2023-01-19 09:00 UTC, merged