add file flag to send-event to specify file containing multiple events
triggermesh/tmctl pull request #336
Opened 2023-06-12 19:51 UTC by NikhilSharmaWe

### Description
This PR adds a `-f` flag to the `send-event` command for specifying the file containing events.

### Motivation
Fixes: #220

2023-06-14 06:10 UTC, tzununbekov requested changes
Looks good, only one tiny comment before the merge.

2023-06-14 06:10 UTC, tzununbekov commented on cmd/sendevent/sendevent.go
> +	fileData, err := ioutil.ReadFile(file)
[`ioutil.ReadFile`](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/io/ioutil/ioutil.go;l=35) is deprecated, please switch to `os.ReadFile`:
```suggestion
	fileData, err := os.ReadFile(file)
```

2023-06-14 12:02 UTC, NikhilSharmaWe commented on cmd/sendevent/sendevent.go
> +	fileData, err := ioutil.ReadFile(file)
Resolved

2023-06-15 07:01 UTC, NikhilSharmaWe commented
@tzununbekov 
Updated the docs

2023-06-15 07:02 UTC, tzununbekov approved these changes

2023-06-15 08:39 UTC, merged